# Generated by Django 5.0.1 on 2024-02-21 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('country_domicile', models.CharField(max_length=72)),
                ('institution_name', models.CharField(max_length=72)),
                ('years_of_reviewing', models.IntegerField(default=0)),
                ('pending_assignments', models.IntegerField(default=0)),
                ('completed_assignments', models.IntegerField(default=0)),
                ('due_assignments', models.IntegerField(default=0)),
                ('overdue_assignments', models.IntegerField(default=0)),
                ('withdrawn_assignments', models.IntegerField(default=0)),
                ('assignments', models.ManyToManyField(blank=True, related_name='projects', to='project.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
