# Generated by Django 5.0.1 on 2024-02-23 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_rename_due_assignments_reviewer_completed_assignments_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='completed_assignments',
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.reviewer')),
            ],
        ),
    ]
