# Generated by Django 5.0.1 on 2024-02-23 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='remark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
