# Generated by Django 5.0.1 on 2024-02-23 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_remark_options_remark_created_at_and_more'),
        ('user', '0007_alter_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.studentorresearcher'),
        ),
    ]
