# Generated by Django 5.0.1 on 2024-02-24 00:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='background',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='project',
            name='hypothesis',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='introduction',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='project',
            name='justification',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='project',
            name='literature_review',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='project',
            name='materials_and_methods',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=150000),
        ),
        migrations.AlterField(
            model_name='project',
            name='objectives',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=35000),
        ),
        migrations.AlterField(
            model_name='project',
            name='procedure',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope_and_limitation',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', max_length=50000),
        ),
    ]
