# Generated by Django 5.0.1 on 2024-02-24 21:56

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0017_alter_project_background_alter_project_hypothesis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsProjectOwner',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.permission')),
            ],
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
