# Generated by Django 5.0.1 on 2024-02-21 21:49

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='user/default.png', null=True, upload_to=user.models.CustomUser.upload_image),
        ),
        migrations.DeleteModel(
            name='Reviewer',
        ),
    ]
