# Generated by Django 5.0.1 on 2024-02-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_isreviewer_isstudentorresearcher_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='track_no',
        ),
        migrations.AddField(
            model_name='customuser',
            name='track_id',
            field=models.UUIDField(null=True),
        ),
    ]
