# Generated by Django 5.0.1 on 2024-02-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_customuser_track_no_customuser_track_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='payment_approved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='track_id',
        ),
    ]
