# Generated by Django 5.0.1 on 2024-02-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('chair', 'Chair'), ('asst chair', 'Assistant chair')], default='chair', max_length=10),
        ),
    ]
